

USE QLDSV_TC
GO

PRINT '=== STARTING COMPLETE SETUP ==='

-- 1. Sửa view Get_Subscribes
IF EXISTS (SELECT * FROM sys.views WHERE name = 'Get_Subscribes')
BEGIN
    DROP VIEW Get_Subscribes
    PRINT 'Dropped old Get_Subscribes view'
END

CREATE VIEW Get_Subscribes AS 
SELECT 'Khoa CNTT' AS TENPHONG, 'localhost' AS TENSERVER 
UNION ALL 
SELECT 'Khoa VT' AS TENPHONG, 'localhost' AS TENSERVER 
UNION ALL 
SELECT 'Ke Toan' AS TENPHONG, 'localhost' AS TENSERVER
GO

PRINT 'Created Get_Subscribes view'

-- 2. Sửa SP_CHECKID
IF EXISTS (SELECT * FROM sys.procedures WHERE name = 'SP_CHECKID')
    DROP PROCEDURE SP_CHECKID
GO

CREATE PROC SP_CHECKID @ID NCHAR(10), @Type NCHAR(20) 
AS 
BEGIN 
    IF(@Type = 'MALOP') 
    BEGIN 
        IF EXISTS(SELECT * FROM dbo.LOP WHERE dbo.LOP.MALOP = @ID) 
            RETURN 1; 
    END 
    IF(@Type = 'MAMONHOC') 
    BEGIN 
        IF EXISTS(SELECT * FROM dbo.MONHOC AS MH WHERE MH.MAMH = @ID) 
            RETURN 1; 
    END 
    IF(@Type = 'MASV') 
    BEGIN 
        IF EXISTS(SELECT * FROM dbo.SINHVIEN WHERE dbo.SINHVIEN.MASV = @ID) 
            RETURN 1; 
    END 
    RETURN 0; 
END
GO

PRINT 'Created SP_CHECKID'

-- 3. Sửa SP_CHECKNAME
IF EXISTS (SELECT * FROM sys.procedures WHERE name = 'SP_CHECKNAME')
    DROP PROCEDURE SP_CHECKNAME
GO

CREATE PROCEDURE SP_CHECKNAME @Name NVARCHAR(200), @Type NVARCHAR(50) 
AS 
BEGIN 
    IF(@Type = 'TENLOP') 
    BEGIN 
        IF EXISTS(SELECT * FROM dbo.LOP WHERE dbo.LOP.TENLOP = @Name) 
            RETURN 1; 
    END 
    IF(@Type = 'TENMONHOC') 
    BEGIN 
        IF EXISTS(SELECT * FROM dbo.MONHOC WHERE TENMH = @Name) 
            RETURN 1; 
    END 
    RETURN 0; 
END
GO

PRINT 'Created SP_CHECKNAME'

-- 4. Tạo login SVIEN cho sinh viên
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = 'SVIEN')
BEGIN
    CREATE LOGIN [SVIEN] WITH PASSWORD = '1', DEFAULT_DATABASE = [QLDSV_TC]
    PRINT 'Created LOGIN: SVIEN'
END

IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'SVIEN')
BEGIN
    CREATE USER [SVIEN] FOR LOGIN [SVIEN]
    PRINT 'Created USER: SVIEN'
END

-- 5. Tạo role SINHVIEN
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'SINHVIEN')
BEGIN
    CREATE ROLE [SINHVIEN]
    PRINT 'Created ROLE: SINHVIEN'
END

ALTER ROLE [SINHVIEN] ADD MEMBER [SVIEN]

-- 6. Cấp quyền cho SINHVIEN
GRANT SELECT ON SINHVIEN TO SINHVIEN
GRANT SELECT ON LOP TO SINHVIEN
GRANT SELECT ON KHOA TO SINHVIEN
GRANT SELECT ON DANGKY TO SINHVIEN
GRANT SELECT ON LOPTINCHI TO SINHVIEN
GRANT SELECT ON MONHOC TO SINHVIEN
GRANT SELECT ON HOCPHI TO SINHVIEN
GRANT SELECT ON CT_DONGHOCPHI TO SINHVIEN

-- Stored procedures cho sinh viên
GRANT EXECUTE ON SP_CHECK_DANGNHAP TO SINHVIEN
GRANT EXECUTE ON SP_CHECK_LOGIN_SV TO SINHVIEN
GRANT EXECUTE ON SP_GET_THONGTINSINHVIEN TO SINHVIEN
GRANT EXECUTE ON SP_GETDIEMSV TO SINHVIEN
GRANT EXECUTE ON SP_GET_NIENKHOA TO SINHVIEN
GRANT EXECUTE ON SP_GET_HOCKY TO SINHVIEN
GRANT EXECUTE ON SP_GET_MONHOC TO SINHVIEN
GRANT EXECUTE ON SP_GET_NHOM TO SINHVIEN
GRANT EXECUTE ON SP_DKY_LTC TO SINHVIEN
GRANT EXECUTE ON SP_HUY_DKY_LTC TO SINHVIEN
GRANT EXECUTE ON SP_GET_LISTLOPTINCHI_DKI TO SINHVIEN
GRANT EXECUTE ON SP_GET_LISTLOPTINCHI_DADKI TO SINHVIEN
GRANT EXECUTE ON SP_SEARCH_LTC TO SINHVIEN
GRANT EXECUTE ON SP_GET_HOCPHI TO SINHVIEN
GRANT EXECUTE ON SP_GET_CTDONG_HOCPHI TO SINHVIEN
GRANT EXECUTE ON SP_CHANGEPASS_FOR_SV TO SINHVIEN

PRINT 'Granted permissions to SINHVIEN'

-- 7. Tạo role GIANGVIEN
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'GIANGVIEN')
BEGIN
    CREATE ROLE [GIANGVIEN]
    PRINT 'Created ROLE: GIANGVIEN'
END

-- 8. Tạo login cho tất cả giáo viên
DECLARE @sql NVARCHAR(MAX)
DECLARE @magv NVARCHAR(10)

DECLARE gv_cursor CURSOR FOR
SELECT MAGV FROM GIANGVIEN

OPEN gv_cursor
FETCH NEXT FROM gv_cursor INTO @magv

WHILE @@FETCH_STATUS = 0
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = @magv)
    BEGIN
        SET @sql = 'CREATE LOGIN [' + @magv + '] WITH PASSWORD = ''1'', DEFAULT_DATABASE = [QLDSV_TC]'
        EXEC sp_executesql @sql
        PRINT 'Created login: ' + @magv
    END
    
    IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = @magv)
    BEGIN
        SET @sql = 'CREATE USER [' + @magv + '] FOR LOGIN [' + @magv + ']'
        EXEC sp_executesql @sql
        PRINT 'Created user: ' + @magv
    END
    
    EXEC sp_addrolemember 'GIANGVIEN', @magv
    
    FETCH NEXT FROM gv_cursor INTO @magv
END

CLOSE gv_cursor
DEALLOCATE gv_cursor

-- 9. Cấp quyền cho GIANGVIEN
GRANT EXECUTE ON SP_CHECK_DANGNHAP TO GIANGVIEN
GRANT EXECUTE ON SP_GetMaKhoa TO GIANGVIEN
GRANT EXECUTE ON SP_CHECKID TO GIANGVIEN
GRANT EXECUTE ON SP_CHECKNAME TO GIANGVIEN
GRANT EXECUTE ON SP_GET_NIENKHOA TO GIANGVIEN
GRANT EXECUTE ON SP_GET_HOCKY TO GIANGVIEN
GRANT EXECUTE ON SP_GET_MONHOC TO GIANGVIEN
GRANT EXECUTE ON SP_GET_NHOM TO GIANGVIEN
GRANT EXECUTE ON SP_UPDATEDIEM TO GIANGVIEN

GRANT SELECT ON GIANGVIEN TO GIANGVIEN
GRANT SELECT ON LOP TO GIANGVIEN
GRANT SELECT ON KHOA TO GIANGVIEN
GRANT SELECT ON SINHVIEN TO GIANGVIEN
GRANT SELECT ON MONHOC TO GIANGVIEN
GRANT SELECT ON LOPTINCHI TO GIANGVIEN
GRANT SELECT ON DANGKY TO GIANGVIEN
GRANT SELECT ON HOCPHI TO GIANGVIEN

GRANT INSERT, UPDATE, DELETE ON LOP TO GIANGVIEN
GRANT INSERT, UPDATE, DELETE ON SINHVIEN TO GIANGVIEN
GRANT INSERT, UPDATE, DELETE ON MONHOC TO GIANGVIEN
GRANT INSERT, UPDATE, DELETE ON LOPTINCHI TO GIANGVIEN
GRANT INSERT, UPDATE, DELETE ON DANGKY TO GIANGVIEN

PRINT 'Granted permissions to GIANGVIEN'

PRINT '=== SETUP COMPLETED SUCCESSFULLY ==='
PRINT ''
PRINT 'Available accounts:'
PRINT '1. Admin: sa/123'
PRINT '2. Teachers: GV01/1, GV02/1, GV03/1, GV04/1, GV05/1, GV06/1'
PRINT '3. Students: N15DCCN001/1, N15DCCN002/1, N15DCCN003/1, N15DCCN004/1'
